# Generated by Django 5.1 on 2025-03-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='statut',
            field=models.CharField(choices=[('EN REGLE', 'EN REGLE'), ('SUSPENDU', 'SUSPENDU'), ('RETIRE', 'RETIRE')], max_length=40, verbose_name='Statut'),
        ),
    ]
