# Generated by Django 5.1 on 2025-03-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agent_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='matricule',
            field=models.CharField(max_length=20, unique=True, verbose_name='Agrement'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='numero_carte',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numero'),
        ),
    ]
