# Generated by Django 5.1 on 2025-03-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtiers', '0002_courtier_delete_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtier',
            name='matricule',
            field=models.CharField(max_length=20, unique=True, verbose_name='Agrement'),
        ),
        migrations.AlterField(
            model_name='courtier',
            name='numero_carte',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numero'),
        ),
    ]
