# Generated by Django 5.1 on 2025-04-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controler',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='controler',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='controler',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controler',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='controler',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='controler',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
