# Generated by Django 5.1 on 2025-04-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleur', '0002_controler_is_active_controler_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controler',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='controler',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='controler',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controler',
            name='nom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controler',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
