# Generated by Django 5.1 on 2025-05-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleur', '0003_controler_adresse_controler_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controler',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
